
AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: >
  Self-Healing-Infra

  SAM Template for Self-Healing Infrastructure Agent

Globals:
  Function:
    Timeout: 3
    LoggingConfig:
      LogFormat: JSON

Resources:



  SelfHealingFaultyLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/kushal/faulty-lambda/
      Handler: index.handler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      Timeout: 10
      AutoPublishAlias: live




  MemoryTestLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/kushal/memory-test-lambda/
      Handler: index.handler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 30



